import { colors } from '../../components/landing/theme'

export const POSTS = [
  {
    id: 'spend-globally-launch',
    category: 'product',
    title: 'Introducing Spend Globally — pay in 200+ countries with naira',
    excerpt: 'Today we ship our most ambitious product yet. Here is how a Lagos-funded wallet now works in Tokyo, Toronto, and 198 other places.',
    author: 'Adaeze Okonkwo',
    authorRole: 'Co-founder & CEO',
    authorBio: 'Adaeze leads VeloxZap. Before this she ran payment products at Flutterwave, where her team built the rails serving over 12 million users.',
    initials: 'AO',
    date: 'Apr 28, 2026',
    readTime: '6 min',
    accent: colors.gold,
    featured: true,
    body: [
      { type: 'p', text: 'For most of our history, "going global" with a Nigerian wallet has meant a frustrating dance — a domiciliary account here, a third-party card there, a workaround everywhere. We built Spend Globally to end that dance.' },
      { type: 'p', text: 'From today, every VeloxZap user can issue a Visa-backed card that spends naira directly in 200+ countries — at the live mid-market rate, with a flat 1.5% spread, and zero hidden fees.' },
      { type: 'h2', text: 'Why we built it' },
      { type: 'p', text: 'Our most-asked support question for two years running was a variation of "can I use my wallet on Amazon US?". The answer used to be no. Then it was "yes, but it costs you 8%". Now it is yes, full stop.' },
      { type: 'quote', text: 'We are not adding a feature. We are removing a tax — the tax that Nigerians pay just to participate in the global economy.', cite: 'Adaeze Okonkwo, Co-founder' },
      { type: 'h2', text: 'How it works' },
      { type: 'list', items: [
        'Open the VeloxZap app and tap the new Cards tab.',
        'Issue your virtual Visa in under 30 seconds — no application form.',
        'Spend anywhere Visa is accepted; we convert at live FX rates with a 1.5% spread.',
        'Freeze, unfreeze, or roll a new card in one tap if anything looks off.',
      ]},
      { type: 'callout', tone: 'gold', text: 'Early access is open to everyone today. The first 10,000 cards ship with a free physical card delivered nationwide.' },
      { type: 'h2', text: 'What\'s next' },
      { type: 'p', text: 'This is the first chapter. Over the coming quarters we will add multi-currency wallets, business cards for SMEs, and travel insurance bundled with every card. We will publish each as we ship it.' },
      { type: 'p', text: 'If you\'ve been waiting on a permission slip to use your money globally, today is the day. Welcome aboard.' },
    ],
  },
  {
    id: 'fraud-engine-2026',
    category: 'security',
    title: 'How our fraud engine stopped ₦4B in attempted theft last quarter',
    excerpt: 'A behind-the-scenes look at the ML pipeline, the human review layer, and the velocity rules that keep your wallet safe.',
    author: 'Tunde Bakare',
    authorRole: 'Co-founder & CTO',
    authorBio: 'Tunde architects the security and infrastructure layers of VeloxZap. Previously a staff engineer at Paystack, where he led anti-fraud systems.',
    initials: 'TB',
    date: 'Apr 18, 2026',
    readTime: '8 min',
    accent: colors.champagne,
    body: [
      { type: 'p', text: 'In Q1 2026, our fraud engine flagged and blocked over ₦4 billion in attempted fraudulent transactions. Here is how it works — and why no two attempts ever look the same.' },
      { type: 'h2', text: 'A three-layer defense' },
      { type: 'p', text: 'Every transaction passes through three independent systems before it settles: a velocity layer, an anomaly model, and — for high-risk events — a human review queue.' },
      { type: 'list', items: [
        'Velocity rules: hard limits on transaction frequency, amounts, and device count per identity.',
        'Behavioral ML: a model trained on 18 months of legitimate user patterns flags outliers in real time.',
        'Human review: anything scored above 0.85 gets eyes from our 24/7 risk team within 90 seconds.',
      ]},
      { type: 'h2', text: 'What we caught' },
      { type: 'p', text: 'The most common attack pattern this quarter was account takeover via SIM-swap. We countered it by tying device fingerprints to wallet credentials — a SIM-swap alone is no longer enough to move funds.' },
      { type: 'callout', tone: 'mute', text: 'If you ever see a login from a device you do not recognize, you can revoke it instantly from Settings → Sessions.' },
      { type: 'p', text: 'Security is not a feature you finish. We will keep publishing what we learn — partly because transparency builds trust, partly because a public methodology is its own deterrent.' },
    ],
  },
  {
    id: 'naira-q2-outlook',
    category: 'insights',
    title: 'The Naira in Q2 2026 — what crypto traders should watch',
    excerpt: 'CBN policy shifts, oil prices, and the diaspora dollar — three forces shaping rates over the next 90 days.',
    author: 'Chiamaka Eze',
    authorRole: 'Co-founder & COO',
    authorBio: 'Chiamaka runs operations and strategy at VeloxZap. Goldman Sachs alum with a decade of African market expansion experience.',
    initials: 'CE',
    date: 'Apr 12, 2026',
    readTime: '5 min',
    accent: colors.gold,
    body: [
      { type: 'p', text: 'Three forces will shape the naira-USD rate over the next 90 days. None of them are surprising — but how they interact is.' },
      { type: 'h2', text: '1. CBN tightening cycle' },
      { type: 'p', text: 'Expect another 50–100bps hike at the next MPC meeting. The trade is already priced into forwards, but spot has lagged. Watch for a 3–4% naira rally if the hike comes in at the upper end.' },
      { type: 'h2', text: '2. Brent oil at $82' },
      { type: 'p', text: 'Brent above $80 is a structural tailwind for FX reserves. Every $5 above $75 adds roughly $1.2B per quarter to inflows. Our base case has reserves climbing toward $38B by July.' },
      { type: 'h2', text: '3. Diaspora dollar' },
      { type: 'p', text: 'Remittances are quietly the most reliable variable. Q1 2026 logged $6.4B in inflows — a record. Crypto-native remittances now make up an estimated 18% of that, up from 9% a year ago.' },
      { type: 'quote', text: 'The naira is no longer a one-variable trade. Anyone trading it on oil alone in 2026 is trading 2014.', cite: 'Chiamaka Eze, COO' },
      { type: 'p', text: 'For VeloxZap traders: tighter spreads on USDT/NGN are likely through April. Beyond that, watch the May MPC.' },
    ],
  },
  {
    id: 'gift-card-trading-101',
    category: 'tutorials',
    title: 'Gift card trading 101 — how to get the best naira rate every time',
    excerpt: 'A practical guide to selling Amazon, iTunes, and Steam cards without leaving rate on the table.',
    author: 'Ifeoluwa Bello',
    authorRole: 'Customer Education Lead',
    authorBio: 'Ife writes the docs, the help center, and the in-app tutorials at VeloxZap. Former secondary school physics teacher.',
    initials: 'IB',
    date: 'Apr 5, 2026',
    readTime: '7 min',
    accent: colors.champagne,
    body: [
      { type: 'p', text: 'Gift card trading sounds simple — until you realize the rate you got was 4% below what you could have. Here is a five-step routine to never leave naira on the table.' },
      { type: 'h2', text: 'Step 1: Check the live rate first' },
      { type: 'p', text: 'Every card type has its own live naira rate, updated continuously. Open the Gift Cards tab and check before you list. Quoted rate at upload is locked, even if the market moves.' },
      { type: 'h2', text: 'Step 2: Pick the right denomination' },
      { type: 'p', text: 'A single $200 Amazon card almost always gets a better rate than two $100 cards. Higher denominations have lower processing overhead, so we pass the savings on.' },
      { type: 'h2', text: 'Step 3: Send a clear photo' },
      { type: 'list', items: [
        'Hold the card flat — no folds or glare.',
        'Make sure all 16 digits of the redemption code are legible.',
        'Use the in-app camera; it auto-corrects perspective.',
      ]},
      { type: 'callout', tone: 'gold', text: 'Photos sent through the in-app camera are processed in 30 seconds. Photos uploaded from your gallery take an average of 4 minutes.' },
      { type: 'h2', text: 'Step 4: Lock the rate' },
      { type: 'p', text: 'The "Lock rate" button at the bottom of the upload screen freezes the quote for 10 minutes. Use it.' },
      { type: 'h2', text: 'Step 5: Watch your wallet' },
      { type: 'p', text: 'Naira hits your wallet within 90 seconds of approval. If anything is delayed past 5 minutes, tap "Help" — our agents respond in under 2 minutes round the clock.' },
    ],
  },
  {
    id: 'series-a-announcement',
    category: 'company',
    title: 'We raised $8M to bring permission-less finance to 200M Africans',
    excerpt: 'Why we partnered with Sequoia Africa, what changes for our users, and what we are building next.',
    author: 'Adaeze Okonkwo',
    authorRole: 'Co-founder & CEO',
    authorBio: 'Adaeze leads VeloxZap. Before this she ran payment products at Flutterwave, where her team built the rails serving over 12 million users.',
    initials: 'AO',
    date: 'Mar 22, 2026',
    readTime: '4 min',
    accent: colors.gold,
    body: [
      { type: 'p', text: 'Today we are announcing $8M in Series A funding, led by Sequoia Africa, with participation from Tiger Global, Y Combinator, and a syndicate of operators we deeply respect.' },
      { type: 'h2', text: 'What this means for our users' },
      { type: 'list', items: [
        'Faster shipping — we are growing the engineering team from 14 to 35 by year-end.',
        'Tighter spreads — capital lets us narrow margins on FX and crypto swaps.',
        '24/7 native-language support across English, Pidgin, Hausa, Igbo and Yoruba.',
      ]},
      { type: 'h2', text: 'Why Sequoia Africa' },
      { type: 'p', text: 'We met three other firms who offered larger checks. We picked Sequoia because their thesis on financial sovereignty in emerging markets matches ours, and because they ship operators alongside capital.' },
      { type: 'quote', text: 'We do not want to be the next Wells Fargo for Africa. We want to be the last permission-asking layer between Africans and their money.', cite: 'Adaeze Okonkwo' },
      { type: 'p', text: 'To the 500,000 of you who got us here — thank you. The mission has not changed. We just have more fuel.' },
    ],
  },
  {
    id: '3ds-default-on',
    category: 'security',
    title: '3D-Secure is now on by default — what this means for you',
    excerpt: 'Every online card transaction now requires biometric or PIN approval. Here is the why and the how.',
    author: 'Tunde Bakare',
    authorRole: 'Co-founder & CTO',
    authorBio: 'Tunde architects the security and infrastructure layers of VeloxZap. Previously a staff engineer at Paystack, where he led anti-fraud systems.',
    initials: 'TB',
    date: 'Mar 14, 2026',
    readTime: '3 min',
    accent: colors.gold,
    body: [
      { type: 'p', text: 'Starting today, every online transaction made with a VeloxZap card requires explicit biometric or PIN approval — even if the merchant does not request it. The card number alone is no longer enough.' },
      { type: 'h2', text: 'Why' },
      { type: 'p', text: 'Card-not-present fraud accounts for 78% of all attempted fraud we see. Most of it relies on a leaked card number plus a guessable CVV. 3D-Secure breaks that economy.' },
      { type: 'callout', tone: 'gold', text: 'You will see a VeloxZap notification ping on every online charge. Tap to approve, swipe to deny. It typically takes 2 seconds.' },
      { type: 'h2', text: 'What if I am offline?' },
      { type: 'p', text: 'For up to 60 seconds, the merchant can complete via a backup PIN you set in Settings → Card. After that, the charge declines and you can retry.' },
      { type: 'p', text: 'A small bit of friction for a large chunk of safety. Worth it.' },
    ],
  },
  {
    id: 'crypto-swap-improvements',
    category: 'product',
    title: 'Faster swaps, tighter spreads — Crypto Swap v3 is live',
    excerpt: 'BTC, USDT and ETH swaps now settle in under 12 seconds with a 0.4% spread. Here is how we got there.',
    author: 'Daniel Adesanya',
    authorRole: 'Head of Engineering',
    authorBio: 'Daniel runs engineering at VeloxZap. Previously at Binance, where he scaled trading systems handling $2B+ daily volume.',
    initials: 'DA',
    date: 'Mar 2, 2026',
    readTime: '5 min',
    accent: colors.champagne,
    body: [
      { type: 'p', text: 'Crypto Swap v3 ships today. Two numbers tell the story: 12 seconds median settlement, and a 0.4% all-in spread.' },
      { type: 'h2', text: 'How we shaved 80% off settlement time' },
      { type: 'list', items: [
        'Co-located our matching engine with three liquidity providers in Frankfurt.',
        'Pre-funded hot wallets so we no longer wait on on-chain confirmations for amounts under ₦5M.',
        'Switched from REST to WebSocket pricing across all our LPs.',
      ]},
      { type: 'h2', text: 'How we tightened the spread' },
      { type: 'p', text: 'We absorbed our 0.3% take-rate into the spread, then renegotiated LP terms based on the volume our customers brought us. The pass-through to you is the difference.' },
      { type: 'callout', tone: 'mute', text: 'Spread is shown live on the swap screen — no surprises at confirmation.' },
      { type: 'p', text: 'If you trade often, v3 should feel like a different product. If you trade occasionally, it should feel like things just got out of your way.' },
    ],
  },
  {
    id: 'pay-bills-tutorial',
    category: 'tutorials',
    title: 'Pay all your bills in one tap — DSTV, GOTV, electricity & more',
    excerpt: 'Setting up auto-pay for your monthly recurring bills takes 90 seconds. Walk through it with us.',
    author: 'Ifeoluwa Bello',
    authorRole: 'Customer Education Lead',
    authorBio: 'Ife writes the docs, the help center, and the in-app tutorials at VeloxZap. Former secondary school physics teacher.',
    initials: 'IB',
    date: 'Feb 24, 2026',
    readTime: '4 min',
    accent: colors.gold,
    body: [
      { type: 'p', text: 'You should never have to remember a due date again. Here is how to set up auto-pay for every recurring bill in your life — DSTV, electricity, internet, water — in 90 seconds flat.' },
      { type: 'h2', text: 'The setup' },
      { type: 'list', items: [
        'Tap the Bills tab and pick your biller.',
        'Enter your account or smart-card number — we validate it instantly.',
        'Pick a renewal cadence: monthly, bi-monthly, or pay-on-low-balance.',
        'Toggle "Auto-pay on" and confirm with biometrics.',
      ]},
      { type: 'h2', text: 'What happens next' },
      { type: 'p', text: 'On the day before each due date, you get a notification with the amount. You can pause or modify any scheduled payment up to 12 hours before it runs. Otherwise it runs silently.' },
      { type: 'callout', tone: 'gold', text: 'Set up three or more auto-pays and you unlock our Bills Loyalty tier — 5% off DSTV and GOTV renewals for life.' },
    ],
  },
  {
    id: 'state-of-african-fintech',
    category: 'insights',
    title: 'The state of African fintech — 5 charts that explain 2026',
    excerpt: 'Adoption is up, fundraising is selective, and the next breakout will be cross-border payments.',
    author: 'Chiamaka Eze',
    authorRole: 'Co-founder & COO',
    authorBio: 'Chiamaka runs operations and strategy at VeloxZap. Goldman Sachs alum with a decade of African market expansion experience.',
    initials: 'CE',
    date: 'Feb 12, 2026',
    readTime: '9 min',
    accent: colors.champagne,
    body: [
      { type: 'p', text: 'African fintech is in its third act. Act one was payments. Act two was wallets. Act three — the one we are starting now — is cross-border money movement at consumer scale.' },
      { type: 'h2', text: 'Adoption is at an all-time high' },
      { type: 'p', text: '47% of urban West Africans now hold at least one fintech wallet, up from 28% in 2023. The bottleneck is no longer education — it is utility.' },
      { type: 'h2', text: 'Fundraising is selective, not slow' },
      { type: 'p', text: 'Total dollars raised by African fintechs are flat year-over-year. But the number of deals is down 35% — meaning capital is concentrating in fewer, larger bets.' },
      { type: 'quote', text: 'The 2026 winner is whoever solves cross-border first. Everything else is a feature.', cite: 'Chiamaka Eze' },
      { type: 'h2', text: 'Where the breakout is' },
      { type: 'list', items: [
        'Stablecoin-rail remittances are growing 9x faster than SWIFT-based ones.',
        'Pan-African settlement (Nigeria → Kenya → Ghana) is still mostly broken — first mover advantage is huge.',
        'B2B FX is the quiet winner: thin margins, deep volume, sticky customers.',
      ]},
      { type: 'p', text: 'If you are an operator, builder or investor in this space — the next 18 months will reward conviction, not coverage.' },
    ],
  },
]

export const findPost = (id) => POSTS.find(p => p.id === id)

export const relatedPosts = (post, n = 3) =>
  POSTS
    .filter(p => p.id !== post.id && p.category === post.category)
    .slice(0, n)
