const CDN = 'https://nigerianbanks.xyz/logo'

// Full Flutterwave NG bank list — logo: null means no real logo, falls back to coloured initials
const bankList = [
  { code: '110005', name: '3Line Card Management Limited',           logo: null },
  { code: '120001', name: '9 Payment Service Bank',                  logo: null },
  { code: '090629', name: '9JaPay Microfinance Bank',                logo: null },
  { code: '050005', name: 'Aaa Finance',                              logo: null },
  { code: '090270', name: 'AB Microfinance Bank',                     logo: null },
  { code: '070010', name: 'Abbey Mortgage Bank',                      logo: null },
  { code: '090260', name: 'Above Only Microfinance Bank',             logo: null },
  { code: '090197', name: 'ABU Microfinance Bank',                    logo: null },
  { code: '090424', name: 'Abucoop Microfinance Bank',               logo: null },
  { code: '090545', name: 'Abulesoro Microfinance Bank Ltd',         logo: null },
  { code: '090202', name: 'Accelerex Network',                        logo: null },
  { code: '044',    name: 'Access Bank',                              logo: `${CDN}/access-bank.png` },
  { code: '063',    name: 'Access Bank Diamond',                     logo: `${CDN}/access-bank-diamond.png` },
  { code: '100013', name: 'AccessMobile',                            logo: null },
  { code: '090134', name: 'Accion Microfinance Bank',                 logo: null },
  { code: '090483', name: 'Ada Microfinance Bank',                   logo: null },
  { code: '070030', name: 'Adamawa Mortgage Bank',                    logo: null },
  { code: '090160', name: 'Addosser Microfinance Bank',               logo: null },
  { code: '090268', name: 'Adeyemi College Staff MFB',                logo: null },
  { code: '51051',  name: 'Advance La Fayette Bank',                 logo: null },
  { code: '90759',  name: 'Advancly MFB',                            logo: null },
  { code: '090292', name: 'Afekhafe Microfinance Bank',               logo: null },
  { code: '090518', name: 'Afemai Microfinance Bank',                logo: null },
  { code: '100028', name: 'AG Mortgage Bank',                        logo: null },
  { code: '090371', name: 'Agosasa Microfinance Bank',                logo: null },
  { code: '090608', name: 'Akpo Microfinance Bank',                  logo: null },
  { code: '090531', name: 'Aku Microfinance Bank',                   logo: null },
  { code: '090561', name: 'Akuchukwu Microfinance Bank Ltd',         logo: null },
  { code: '070025', name: 'Akwa Savings & Loans Limited',             logo: null },
  { code: '090133', name: 'AL-Barakah Microfinance Bank',             logo: null },
  { code: '090277', name: 'Al-Hayat Microfinance Bank',               logo: null },
  { code: '035A',   name: 'ALAT by WEMA',                            logo: `${CDN}/alat-by-wema.png` },
  { code: '090259', name: 'Alekun Microfinance Bank',                 logo: null },
  { code: '090297', name: 'Alert Microfinance Bank',                  logo: null },
  { code: '090131', name: 'Allworkers Microfinance Bank',             logo: null },
  { code: '090548', name: 'Ally Microfinance Bank',                  logo: null },
  { code: '090169', name: 'Alpha Kapital Microfinance Bank',          logo: null },
  { code: '000041', name: 'Alpha Morgan Bank',                        logo: null },
  { code: '000037', name: 'Alternative Bank Limited',                 logo: null },
  { code: '090489', name: 'Alvana Microfinance Bank',                logo: null },
  { code: '050045', name: 'Amaanah Finance',                          logo: null },
  { code: '090394', name: 'Amac Microfinance Bank',                   logo: null },
  { code: '090180', name: 'AMJU Unique Microfinance Bank',            logo: null },
  { code: '090116', name: 'AMML MFB',                                 logo: null },
  { code: '090610', name: 'Amoye Microfinance Bank',                 logo: null },
  { code: '90770',  name: 'Ample MFB',                               logo: null },
  { code: '090476', name: 'Anchorage Microfinance Bank',             logo: null },
  { code: '090469', name: 'Aniocha Microfinance Bank',               logo: null },
  { code: '090143', name: 'Apeks Microfinance Bank',                  logo: null },
  { code: '090737', name: 'Apex Trust MFB',                          logo: null },
  { code: '090376', name: 'Apple Microfinance Bank',                  logo: null },
  { code: '090307', name: 'Aramoko Microfinance Bank',                logo: null },
  { code: '110011', name: 'Arca Payments',                           logo: null },
  { code: '090282', name: 'Arise Microfinance Bank',                  logo: null },
  { code: '090816', name: 'ARM Microfinance Bank',                   logo: null },
  { code: '090001', name: 'ASO Savings & Loans',                      logo: `${CDN}/asosavings.png` },
  { code: '401',    name: 'ASO Savings and Loans',                    logo: `${CDN}/asosavings.png` },
  { code: '090544', name: 'Aspire Microfinance Bank Ltd',            logo: null },
  { code: '090287', name: 'Assets Matrix Microfinance Bank',          logo: null },
  { code: '090473', name: 'Assets Microfinance Bank',                logo: null },
  { code: '090172', name: 'Astrapolaris Microfinance Bank',           logo: null },
  { code: '090451', name: 'Atbu Microfinance Bank',                  logo: null },
  { code: '090264', name: 'Auchi Microfinance Bank',                  logo: null },
  { code: '090817', name: 'Auchi Poly Microfinance Bank',            logo: null },
  { code: '090600', name: 'Ave Maria Microfinance Bank Ltd',         logo: null },
  { code: '090478', name: 'Avuenegbe Microfinance Bank',             logo: null },
  { code: '090540', name: 'Aztec Microfinance Bank',                 logo: null },
  { code: '090729', name: 'Babcock Microfinance Bank',               logo: null },
  { code: '090188', name: 'Baines Credit Microfinance Bank',          logo: null },
  { code: '090563', name: 'Balera Microfinance Bank Ltd',            logo: null },
  { code: '090181', name: 'Balogun Fulani Microfinance Bank',         logo: null },
  { code: '090326', name: 'Balogun Gambari Microfinance Bank',        logo: null },
  { code: '090581', name: 'Banc Corp Microfinance Bank',             logo: null },
  { code: '090425', name: 'Banex Microfinance Bank',                 logo: null },
  { code: '090866', name: 'Bank78 Microfinance Bank',                logo: null },
  { code: '090789', name: 'Bankeasy MFB',                            logo: null },
  { code: '090275', name: 'BANKIT MFB',                               logo: null },
  { code: '090529', name: 'Bankly Microfinance Bank',                logo: null },
  { code: '090136', name: 'Baobab Microfinance Bank',                 logo: null },
  { code: '090783', name: 'Barnawa MFB',                             logo: null },
  { code: '090316', name: 'Bayero Microfinance Bank',                 logo: null },
  { code: '090127', name: 'BC Kash Microfinance Bank',                logo: null },
  { code: '090413', name: 'Benysta Microfinance Bank',                logo: null },
  { code: '090615', name: 'Beststar Microfinance Bank',              logo: null },
  { code: '100052', name: 'Beta-Access Yello',                       logo: null },
  { code: '090336', name: 'Bipc Microfinance Bank',                   logo: null },
  { code: '090555', name: 'Bishopgate Microfinance Bank',            logo: null },
  { code: '090977', name: 'Bloc Microfinance Bank',                  logo: null },
  { code: '090743', name: 'Bloom MFB',                               logo: null },
  { code: '090538', name: 'Blue Investments Microfinance Bank',      logo: null },
  { code: '090431', name: 'Bluewhales Microfinance Bank',            logo: null },
  { code: '090117', name: 'Boctrust Microfinance Bank',               logo: null },
  { code: '090444', name: 'Boi Mf Bank',                             logo: null },
  { code: '090494', name: 'Boji Boji Microfinance Bank',             logo: null },
  { code: '090753', name: 'Bold Microfinance Bank',                  logo: null },
  { code: '090319', name: 'Bonghe Microfinance Bank',                 logo: null },
  { code: '090819', name: 'Boost Microfinance Bank',                 logo: null },
  { code: '090395', name: 'Borgu Microfinance Bank',                  logo: null },
  { code: '090508', name: 'Borno Renaissance Microfinance Bank',     logo: null },
  { code: '090501', name: 'Boromu Microfinance Bank',                logo: null },
  { code: '090454', name: 'Borstal Microfinance Bank',               logo: null },
  { code: '090176', name: 'Bosak Microfinance Bank',                  logo: null },
  { code: '090148', name: 'Bowen Microfinance Bank',                  logo: null },
  { code: '090804', name: 'Bowman Microfinance Bank',                logo: null },
  { code: '050006', name: 'Branch International Finance',             logo: null },
  { code: '070015', name: 'Brent Mortgage Bank',                      logo: null },
  { code: '090293', name: 'Brethren Microfinance Bank',               logo: null },
  { code: '090393', name: 'Bridgeway Microfinance Bank',              logo: null },
  { code: '090308', name: 'Brightway Microfinance Bank',              logo: null },
  { code: '090568', name: 'Broadview Microfinance Bank Ltd',         logo: null },
  { code: '090512', name: 'Bubayero Microfinance Bank',              logo: null },
  { code: '110021', name: 'Bud Infrastructure Limited',              logo: null },
  { code: '090613', name: 'Build Microfinance Bank',                 logo: null },
  { code: '090406', name: 'Business Support Microfinance Bank',       logo: null },
  { code: '090415', name: 'Calabar Microfinance Bank',                logo: null },
  { code: '090509', name: 'Capitalmetriq Swift Microfinance Bank',   logo: null },
  { code: '110023', name: 'Capricorn Digital',                       logo: null },
  { code: '090445', name: 'Capstone Mf Bank',                        logo: null },
  { code: '100026', name: 'Carbon',                                  logo: null },
  { code: '090472', name: 'Caretaker Microfinance Bank',             logo: null },
  { code: '090848', name: 'Casha Microfinance Bank',                 logo: null },
  { code: '090634', name: 'Cashbridge Microfinance Bank',            logo: null },
  { code: '090360', name: 'Cashconnect Microfinance Bank',            logo: null },
  { code: '090649', name: 'Cashrite Microfinance Bank',              logo: null },
  { code: '090498', name: 'Catland Microfinance Bank',               logo: null },
  { code: '999001', name: 'CBN TSA',                                 logo: null },
  { code: '090562', name: 'Cedar Microfinance Bank Ltd',             logo: null },
  { code: '100005', name: 'Cellulant',                               logo: null },
  { code: '110012', name: 'Cellulant PSSP',                          logo: null },
  { code: '090154', name: 'CEMCS Microfinance Bank',                  logo: `${CDN}/cemcs-microfinance-bank.png` },
  { code: '50823',  name: 'CEMCS Microfinance Bank',                  logo: `${CDN}/cemcs-microfinance-bank.png` },
  { code: '000028', name: 'Central Bank Of Nigeria',                  logo: null },
  { code: '50032',  name: 'Centrum Finance',                         logo: null },
  { code: '050043', name: 'Ceviant Finance Limited',                  logo: null },
  { code: '303',    name: 'ChamsMobile',                             logo: null },
  { code: '090397', name: 'Chanelle Bank',                            logo: null },
  { code: '090815', name: 'Charis Microfinance Bank',                logo: null },
  { code: '090523', name: 'Chase Microfinance Bank',                 logo: null },
  { code: '090440', name: 'Cherish Microfinance Bank',               logo: null },
  { code: '090416', name: 'Chibueze Microfinance Bank',               logo: null },
  { code: '090141', name: 'Chikum Microfinance Bank',                 logo: null },
  { code: '090490', name: 'Chukwunenye Microfinance Bank',           logo: null },
  { code: '090144', name: 'CIT Microfinance Bank',                    logo: null },
  { code: '023',    name: 'Citi Bank',                                logo: `${CDN}/citibank-nigeria.png` },
  { code: '090343', name: 'Citizen Trust Microfinance Bank Ltd',      logo: null },
  { code: '090482', name: 'Clearpay Microfinance Bank',              logo: null },
  { code: '090511', name: 'Cloverleaf Microfinance Bank',            logo: null },
  { code: '090254', name: 'Coalcamp Microfinance Bank',               logo: null },
  { code: '090374', name: 'Coastline Microfinance Bank',              logo: null },
  { code: '090530', name: 'Confidence Microfinance Bank Ltd',        logo: null },
  { code: '090553', name: 'Consistent Trust Microfinance Bank Ltd',  logo: null },
  { code: '090130', name: 'Consumer Microfinance Bank',               logo: null },
  { code: '070021', name: 'Coop Mortgage Bank',                       logo: null },
  { code: '090365', name: 'Corestep Microfinance Bank',               logo: null },
  { code: '060001', name: 'Coronation Merchant Bank',                 logo: null },
  { code: '050001', name: 'County Finance Ltd',                       logo: null },
  { code: '070006', name: 'Covenant Microfinance Bank',               logo: null },
  { code: '090159', name: 'Credit Afrique Microfinance Bank',         logo: null },
  { code: '110049', name: 'Credit Direct Limited',                   logo: null },
  { code: '090611', name: 'Creditville Microfinance Bank',           logo: null },
  { code: '090526', name: 'Crescent Microfinance Bank',              logo: null },
  { code: '090429', name: 'Crossriver Microfinance Bank',            logo: null },
  { code: '110017', name: 'Crowdforce',                              logo: null },
  { code: '090414', name: 'Crutech Microfinance Bank',                logo: null },
  { code: '110014', name: 'Cyberspace Limited',                      logo: null },
  { code: '090802', name: 'Dabtikir Microfinance Bank',              logo: null },
  { code: '090391', name: 'Davodani Microfinance Bank',               logo: null },
  { code: '090167', name: 'Daylight Microfinance Bank',               logo: null },
  { code: '070023', name: 'Delta Trust Mortgage Bank',                logo: null },
  { code: '090723', name: 'Destiny MFB',                             logo: null },
  { code: '090978', name: 'Dew Microfinance Bank',                   logo: null },
  { code: '090745', name: 'Digitvant MFB',                           logo: null },
  { code: '050013', name: 'Dignity Finance',                          logo: null },
  { code: '090828', name: 'Dilon Microfinance Bank',                 logo: null },
  { code: '090404', name: 'Doje Microfinance Bank Limited',           logo: null },
  { code: '090470', name: 'DOT Microfinance Bank',                   logo: null },
  { code: '090821', name: 'DSC Microfinance Bank',                   logo: null },
  { code: '090721', name: 'DW MFB',                                  logo: null },
  { code: '090156', name: 'e-Barcs Microfinance Bank',                logo: null },
  { code: '090294', name: 'Eagle Flight Microfinance Bank',           logo: null },
  { code: '100021', name: 'Eartholeum',                              logo: null },
  { code: '090707', name: 'Eastman Microfinance Bank',               logo: null },
  { code: '090427', name: 'Ebsu Microfinance Bank',                  logo: null },
  { code: '050',    name: 'EcoBank PLC',                              logo: `${CDN}/ecobank-nigeria.png` },
  { code: '100008', name: 'Ecobank Xpress Account',                  logo: null },
  { code: '100030', name: 'EcoMobile',                               logo: null },
  { code: '090310', name: 'Edfin Microfinance Bank',                  logo: null },
  { code: '090556', name: 'Egwafin Microfinance Bank Ltd',           logo: null },
  { code: '090389', name: 'Ek-Reliable Microfinance Bank',            logo: null },
  { code: '090552', name: 'Ekimogun Microfinance Bank',              logo: null },
  { code: '090097', name: 'Ekondo MFB',                               logo: `${CDN}/ekondo-microfinance-bank.png` },
  { code: '562',    name: 'Ekondo Microfinance Bank',                 logo: `${CDN}/ekondo-microfinance-bank.png` },
  { code: '090273', name: 'Emeralds Microfinance Bank',               logo: null },
  { code: '090114', name: 'Empire Trust MFB',                         logo: null },
  { code: '000033', name: 'ENaira',                                   logo: null },
  { code: '050012', name: 'Enco Finance',                             logo: null },
  { code: '090539', name: 'Enrich Microfinance Bank',                logo: null },
  { code: '000019', name: 'Enterprise Bank',                          logo: null },
  { code: '090872', name: 'Equator Microfinance Bank',               logo: null },
  { code: '090189', name: 'Esan Microfinance Bank',                   logo: null },
  { code: '090166', name: 'Eso-E Microfinance Bank',                  logo: null },
  { code: '100006', name: 'eTranzact',                               logo: null },
  { code: '090304', name: 'Evangel Microfinance Bank',                logo: null },
  { code: '090332', name: 'Evergreen Microfinance Bank',              logo: null },
  { code: '050034', name: 'Evib Finance',                             logo: null },
  { code: '090572', name: 'Ewt Microfinance Bank',                   logo: null },
  { code: '090541', name: 'Excellent Microfinance Bank',             logo: null },
  { code: '090328', name: 'Eyowo MFB',                                logo: null },
  { code: '090551', name: 'Fairmoney Microfinance Bank Ltd',         logo: null },
  { code: '090330', name: 'Fame Microfinance Bank',                   logo: null },
  { code: '050009', name: 'Fast Credit',                              logo: null },
  { code: '090179', name: 'FAST Microfinance Bank',                   logo: null },
  { code: '100014', name: 'FBNMobile',                               logo: null },
  { code: '060002', name: 'FBNQuest Merchant Bank',                   logo: null },
  { code: '100031', name: 'FCMB Easy Account',                       logo: null },
  { code: '090409', name: 'FCMB Microfinance Bank',                   logo: null },
  { code: '090290', name: 'Fct Microfinance Bank',                    logo: null },
  { code: '090398', name: 'Federal Polytechnic Nekede MFB',           logo: null },
  { code: '090298', name: 'Federalpoly Nasarawa MFB',                 logo: null },
  { code: '100001', name: 'FET',                                     logo: null },
  { code: '050002', name: 'Fewchore Finance Company Limited',         logo: null },
  { code: '090153', name: 'FFS Microfinance Bank',                    logo: null },
  { code: '070026', name: 'Fha Mortgage Bank Ltd',                    logo: null },
  { code: '070',    name: 'Fidelity Bank',                            logo: `${CDN}/fidelity-bank.png` },
  { code: '100019', name: 'Fidelity Mobile',                         logo: null },
  { code: '090126', name: 'Fidfund Microfinance Bank',                logo: null },
  { code: '090507', name: 'Fims Microfinance Bank',                  logo: null },
  { code: '608',    name: 'Finatrust Microfinance Bank',             logo: null },
  { code: '090400', name: 'Finca Microfinance Bank',                  logo: null },
  { code: '090366', name: 'Firmus MFB',                               logo: null },
  { code: '110004', name: 'First Apple Limited',                     logo: null },
  { code: '011',    name: 'First Bank PLC',                           logo: `${CDN}/first-bank-of-nigeria.png` },
  { code: '214',    name: 'First City Monument Bank',                 logo: `${CDN}/first-city-monument-bank.png` },
  { code: '070014', name: 'First Generation Mortgage Bank',           logo: null },
  { code: '090479', name: 'First Heritage Microfinance Bank',        logo: null },
  { code: '090868', name: 'First Lowland Microfinance Bank',         logo: null },
  { code: '090163', name: 'First Multiple Microfinance Bank',         logo: null },
  { code: '090285', name: 'First Option Microfinance Bank',           logo: null },
  { code: '090164', name: 'First Royal Microfinance Bank',            logo: null },
  { code: '050022', name: 'FirstMarina Trust Finance',                logo: null },
  { code: '090575', name: 'Firstmidas Microfinance Bank Ltd',        logo: null },
  { code: '090107', name: 'FirstTrust Mortgage Bank',                 logo: null },
  { code: '090614', name: 'Flourish MFB',                            logo: null },
  { code: '110002', name: 'Flutterwave Technology Solutions Limited', logo: null },
  { code: '090709', name: 'Focus Microfinance Bank',                 logo: null },
  { code: '090521', name: 'Foresight Microfinance Bank',             logo: null },
  { code: '070002', name: 'Fortis Microfinance Bank',                 logo: null },
  { code: '100016', name: 'FortisMobile',                            logo: null },
  { code: '090486', name: 'Fortress Microfinance Bank',              logo: null },
  { code: '400001', name: 'FSDH Merchant Bank',                      logo: null },
  { code: '090318', name: 'FUD MFB',                                  logo: null },
  { code: '090145', name: 'Fullrange Microfinance Bank',              logo: null },
  { code: '050010', name: 'Fundquest Financial Services Ltd',         logo: null },
  { code: '090438', name: 'Futminna Microfinance Bank',              logo: null },
  { code: '090158', name: 'Futo Microfinance Bank',                   logo: null },
  { code: '090591', name: 'Gabsyn Microfinance Bank',                logo: null },
  { code: '050033', name: 'Gadol Finance',                            logo: null },
  { code: '090484', name: 'Garki Microfinance Bank',                 logo: null },
  { code: '090168', name: 'Gashua Microfinance Bank',                 logo: null },
  { code: '070009', name: 'Gateway Mortgage Bank',                    logo: null },
  { code: '090579', name: 'Gbede Microfinance Bank',                 logo: null },
  { code: '090475', name: 'Giant Stride Microfinance Bank',          logo: null },
  { code: '090621', name: 'Gidauniyar Alheri Microfinance Bank',     logo: null },
  { code: '090411', name: 'Giginya Microfinance Bank',                logo: null },
  { code: '090186', name: 'Girei Microfinance Bank',                  logo: null },
  { code: '090441', name: 'Giwa Microfinance Bank',                  logo: null },
  { code: '000027', name: 'Globus Bank',                              logo: `${CDN}/globus-bank.png` },
  { code: '00103',  name: 'Globus Bank',                              logo: `${CDN}/globus-bank.png` },
  { code: '090278', name: 'Glory Microfinance Bank',                  logo: null },
  { code: '090408', name: 'Gmb Microfinance Bank',                    logo: null },
  { code: '090574', name: 'Goldman Microfinance Bank',               logo: null },
  { code: '090586', name: 'Gombe Microfinance Bank Ltd',             logo: null },
  { code: '100022', name: 'GoMoney',                                 logo: null },
  { code: '090467', name: 'Good Neighbours Microfinance Bank',       logo: null },
  { code: '090122', name: 'Gowans Microfinance Bank',                 logo: null },
  { code: '090335', name: 'Grant MF Bank',                            logo: null },
  { code: '090857', name: 'Granule Microfinance Bank',               logo: null },
  { code: '090550', name: 'Green Energy Microfinance Bank Ltd',      logo: null },
  { code: '090599', name: 'Greenacres MFB',                          logo: null },
  { code: '090178', name: 'GreenBank Microfinance Bank',              logo: null },
  { code: '090269', name: 'Greenville Microfinance Bank',             logo: null },
  { code: '060004', name: 'Greenwich Merchant Bank',                  logo: null },
  { code: '090195', name: 'Grooming Microfinance Bank',               logo: null },
  { code: '090385', name: 'Gti Microfinance Bank',                    logo: null },
  { code: '100009', name: 'GTMobile',                                logo: null },
  { code: '058',    name: 'Guaranty Trust Bank',                      logo: `${CDN}/guaranty-trust-bank.png` },
  { code: '090500', name: 'Gwong Microfinance Bank',                 logo: null },
  { code: '090147', name: 'Hackman Microfinance Bank',                logo: null },
  { code: '070017', name: 'Haggai Mortgage Bank Limited',             logo: null },
  { code: '090291', name: 'Halacredit Microfinance Bank',             logo: null },
  { code: '090980', name: 'Hamada Microfinance Bank',                logo: null },
  { code: '090121', name: 'Hasal Microfinance Bank',                  logo: null },
  { code: '090363', name: 'Headway Microfinance Bank',                logo: null },
  { code: '100017', name: 'Hedonmark',                               logo: null },
  { code: '030',    name: 'Heritage Bank',                            logo: `${CDN}/heritage-bank.png` },
  { code: '090418', name: 'Highland Microfinance Bank',               logo: null },
  { code: '90761',  name: 'Hillpost MFB',                            logo: null },
  { code: '070024', name: 'Homebase Mortgage',                        logo: null },
  { code: '120002', name: 'HopePSB',                                 logo: null },
  { code: '090598', name: 'IBA MFB',                                 logo: null },
  { code: '090115', name: 'IBANK Microfinance Bank',                  logo: null },
  { code: '090697', name: 'IBBU MFB',                                logo: null },
  { code: '090439', name: 'Ibeto Microfinance Bank',                 logo: null },
  { code: '090118', name: 'IBILE Microfinance Bank',                  logo: null },
  { code: '090532', name: 'Ibolo Microfinance Bank Ltd',             logo: null },
  { code: '090519', name: 'Ibom Fadama Microfinance Bank',           logo: null },
  { code: '090488', name: 'Ibu-Aje Microfinance',                    logo: null },
  { code: '090520', name: 'IC Global Microfinance Bank',             logo: null },
  { code: '090803', name: 'Igbo-Ukwu MFB',                           logo: null },
  { code: '090725', name: 'Ihiala MFB',                              logo: null },
  { code: '090730', name: 'Ijare MFB',                               logo: null },
  { code: '090546', name: 'Ijebu-Ife Microfinance Bank Ltd',         logo: null },
  { code: '090324', name: 'Ikenne Microfinance Bank',                 logo: null },
  { code: '090799', name: 'Ikere MFB',                               logo: null },
  { code: '090279', name: 'Ikire Microfinance Bank',                  logo: null },
  { code: '090536', name: 'Ikoyi-Osun Microfinance Bank',            logo: null },
  { code: '090571', name: 'Ilaro Poly Microfinance Bank Ltd',        logo: null },
  { code: '090370', name: 'Ilasan Microfinance Bank',                 logo: null },
  { code: '090350', name: 'Illorin Microfinance Bank',                logo: null },
  { code: '090430', name: 'Ilora Microfinance Bank',                 logo: null },
  { code: '090834', name: 'Ilutitun-Osoro Microfinance Bank',        logo: null },
  { code: '090258', name: 'Imo State Microfinance Bank',              logo: null },
  { code: '090417', name: 'Imowo Microfinance Bank',                  logo: null },
  { code: '100024', name: 'Imperial Homes Mortgage Bank',            logo: null },
  { code: '090772', name: 'Indulge Microfinance Bank',               logo: null },
  { code: '090838', name: 'Ineba Gogo Microfinance Bank Limited',    logo: null },
  { code: '090157', name: 'Infinity Microfinance Bank',               logo: null },
  { code: '070016', name: 'Infinity Trust Mortgage Bank',             logo: null },
  { code: '100029', name: 'Innovectives Kesh',                       logo: null },
  { code: '090434', name: 'Insight Microfinance Bank',               logo: null },
  { code: '100027', name: 'Intellifin',                              logo: null },
  { code: '090386', name: 'Interland Microfinance Bank',              logo: null },
  { code: '110010', name: 'Interswitch Financial Inclusion Services', logo: null },
  { code: '110003', name: 'Interswitch Limited',                     logo: null },
  { code: '090493', name: 'Iperu Microfinance Bank',                 logo: null },
  { code: '090149', name: 'IRL Microfinance Bank',                    logo: null },
  { code: '090377', name: 'Isaleoyo Microfinance Bank',               logo: null },
  { code: '090428', name: 'Ishie Microfinance Bank',                 logo: null },
  { code: '090849', name: 'Isi Uzo Microfinance Bank Limited',       logo: null },
  { code: '090584', name: 'Island Microfinance Bank',                logo: null },
  { code: '090701', name: 'Isua Microfinance Bank',                  logo: null },
  { code: '090353', name: 'Isuofia Microfinance Bank',                logo: null },
  { code: '090211', name: 'Itex Integrated Services Limited',         logo: null },
  { code: '090578', name: 'Iwade Microfinance Bank Ltd',             logo: null },
  { code: '090543', name: 'Iwoama Microfinance Bank',                logo: null },
  { code: '090570', name: 'Iyamoye Microfinance Bank Ltd',           logo: null },
  { code: '090337', name: 'Iyeru Okin Microfinance Bank Ltd',         logo: null },
  { code: '090421', name: 'Izon Microfinance Bank',                   logo: null },
  { code: '301',    name: 'Jaiz Bank',                               logo: null },
  { code: '090352', name: 'Jessefield Microfinance Bank',             logo: null },
  { code: '090003', name: 'Jubilee-Life Mortgage Bank',               logo: null },
  { code: '110008', name: 'Kadick Integration Limited',              logo: null },
  { code: '090320', name: 'Kadpoly Microfinance Bank',                logo: null },
  { code: '090800', name: 'Kaizen Microfinance Bank',                logo: null },
  { code: '090592', name: 'Kano Poly MFB',                           logo: null },
  { code: '090554', name: 'Kayvee Microfinance Bank',                logo: null },
  { code: '090549', name: 'Kc Microfinance Bank',                    logo: null },
  { code: '090191', name: 'KCMB Microfinance Bank',                   logo: null },
  { code: '070031', name: 'Kebbi State Home Savings and Loans',       logo: null },
  { code: '100015', name: 'Kegow',                                   logo: null },
  { code: '100036', name: 'Kegow (Chamsmobile)',                     logo: null },
  { code: '090602', name: 'Kenechukwu Microfinance Bank',            logo: null },
  { code: '082',    name: 'Keystone Bank',                            logo: `${CDN}/keystone-bank.png` },
  { code: '090487', name: 'Kingdom College Microfinance Bank',       logo: null },
  { code: '090606', name: 'KKU Microfinance Bank',                   logo: null },
  { code: '090865', name: 'Koboweb Microfinance Bank',               logo: null },
  { code: '090480', name: 'Kolomoni Microfinance Bank',              logo: null },
  { code: '010025', name: 'KongaPay',                                 logo: null },
  { code: '090299', name: 'Kontagora Microfinance Bank',              logo: null },
  { code: '110022', name: 'Koraypay',                                logo: null },
  { code: '090380', name: 'Kredi Money Microfinance Bank',            logo: null },
  { code: '090267', name: 'Kuda',                                     logo: `${CDN}/kuda-bank.png` },
  { code: '50211',  name: 'Kuda Bank',                                logo: `${CDN}/kuda-bank.png` },
  { code: '090450', name: 'Kwasu Mf Bank',                           logo: null },
  { code: '090155', name: 'La Fayette Microfinance Bank',             logo: null },
  { code: '070012', name: 'Lagos Building Investment Company',        logo: null },
  { code: '090422', name: 'Landgold Microfinance Bank',               logo: null },
  { code: '090177', name: 'Lapo Microfinance Bank',                   logo: null },
  { code: '090271', name: 'Lavender Microfinance Bank',               logo: null },
  { code: '090724', name: 'Lawyers MFB',                             logo: null },
  { code: '110044', name: 'Leadremit Limited',                       logo: null },
  { code: '090372', name: 'Legend Microfinance Bank',                 logo: null },
  { code: '090420', name: 'Letshego MFB',                             logo: null },
  { code: '090731', name: 'Levite MFB',                              logo: null },
  { code: '090557', name: 'Lifegate Microfinance Bank Ltd',          logo: null },
  { code: '090477', name: 'Light Microfinance Bank',                 logo: null },
  { code: '090807', name: 'Lightway Microfinance Bank',              logo: null },
  { code: '090435', name: 'Links Microfinance Bank',                 logo: null },
  { code: '090780', name: 'Liquidcrest MFB',                         logo: null },
  { code: '090537', name: 'Lobrem Microfinance Bank',                logo: null },
  { code: '090620', name: 'Loma Microfinance Bank',                  logo: null },
  { code: '000029', name: 'Lotus Bank',                               logo: `${CDN}/lotus-bank.png` },
  { code: '303',    name: 'Lotus Bank',                               logo: `${CDN}/lotus-bank.png` },
  { code: '090265', name: 'Lovonus Microfinance Bank',                logo: null },
  { code: '100035', name: 'M36',                                     logo: null },
  { code: '90764',  name: 'Maal MFB',                                logo: null },
  { code: '090623', name: 'Mab Allianz MFB',                         logo: null },
  { code: '090603', name: 'Macrod MFB',                              logo: null },
  { code: '090605', name: 'Madobi Microfinance Bank',                logo: null },
  { code: '090746', name: 'Maestro MFB',                             logo: null },
  { code: '090323', name: 'Mainland Microfinance Bank',               logo: null },
  { code: '090171', name: 'Mainstreet Microfinance Bank',             logo: null },
  { code: '090465', name: 'Maintrust Microfinance Bank',             logo: null },
  { code: '090174', name: 'Malachy Microfinance Bank',                logo: null },
  { code: '090383', name: 'Manny Microfinance Bank',                  logo: null },
  { code: '090410', name: 'Maritime Microfinance Bank',               logo: null },
  { code: '090423', name: 'MAUTECH Microfinance Bank',                logo: null },
  { code: '090843', name: 'Maxitrust Microfinance Bank',             logo: null },
  { code: '090854', name: 'Mayden Microfinance Bank',                logo: null },
  { code: '090321', name: 'Mayfair Microfinance Bank',                logo: null },
  { code: '070019', name: 'Mayfresh Mortgage Bank',                   logo: null },
  { code: '090612', name: 'Medef Microfinance Bank',                 logo: null },
  { code: '090824', name: 'Mega Microfinance Bank',                  logo: null },
  { code: '090280', name: 'Megapraise Microfinance Bank',             logo: null },
  { code: '090867', name: 'Memento Microfinance Bank',               logo: null },
  { code: '090432', name: 'Memphis Microfinance Bank',               logo: null },
  { code: '090589', name: 'Mercury MFB',                             logo: null },
  { code: '090528', name: 'Mgbidi Microfinance Bank',                logo: null },
  { code: '090859', name: 'MIA Microfinance Bank',                   logo: null },
  { code: '090659', name: 'Michael Okpara Uniagric Microfinance Bank',logo: null },
  { code: '090587', name: 'Microbiz Microfinance Bank',              logo: null },
  { code: '110018', name: 'Microsystems Investment and Development Limited', logo: null },
  { code: '090113', name: 'Microvis Microfinance Bank',               logo: null },
  { code: '090192', name: 'Midland Microfinance Bank',                logo: null },
  { code: '090763', name: 'Mint Microfinance Bank',                  logo: null },
  { code: '090281', name: 'Mint-Finex Microfinance Bank',             logo: null },
  { code: '090455', name: 'Mkobo Microfinance Bank Ltd',             logo: null },
  { code: '100011', name: 'Mkudi',                                   logo: null },
  { code: '090775', name: 'Model Microfinance Bank',                 logo: null },
  { code: '090362', name: 'Molusi Microfinance Bank',                 logo: null },
  { code: '120003', name: 'Momo PSB',                                logo: null },
  { code: '090462', name: 'Monarch Microfinance Bank',               logo: null },
  { code: '120005', name: 'Money Master PSB',                        logo: null },
  { code: '090129', name: 'Money Trust Microfinance Bank',            logo: null },
  { code: '100020', name: 'MoneyBox',                                logo: null },
  { code: '090692', name: 'Moneytronics Microfinance Bank',          logo: null },
  { code: '50515',  name: 'Moniepoint MFB',                           logo: `${CDN}/moniepoint-mfb-ng.png` },
  { code: '090405', name: 'Moniepoint Microfinance Bank',             logo: `${CDN}/moniepoint-mfb-ng.png` },
  { code: '090685', name: 'Moremonee Microfinance Bank Limited',     logo: null },
  { code: '090979', name: 'Movasco-Op Microfinance Bank',            logo: null },
  { code: '090448', name: 'Moyofade Mf Bank',                        logo: null },
  { code: '090392', name: 'Mozfin Microfinance Bank',                 logo: null },
  { code: '090190', name: 'Mutual Benefits Microfinance Bank',        logo: null },
  { code: '090151', name: 'Mutual Trust Microfinance Bank',           logo: null },
  { code: '090740', name: 'NAF MFB',                                 logo: null },
  { code: '090152', name: 'Nagarta Microfinance Bank',                logo: null },
  { code: '090349', name: 'Nasarawa Microfinance Bank',               logo: null },
  { code: '090263', name: 'Navy Microfinance Bank',                   logo: null },
  { code: '090128', name: 'Ndiorah Microfinance Bank',                logo: null },
  { code: '090329', name: 'Neptune Microfinance Bank',                logo: null },
  { code: '110025', name: 'Netapps Technology Limited',              logo: null },
  { code: '090205', name: 'New Dawn Microfinance Bank',               logo: null },
  { code: '090378', name: 'New Golden Pastures Microfinance Bank',    logo: null },
  { code: '090108', name: 'New Prudential Bank',                      logo: null },
  { code: '050004', name: 'Newedge Finance Ltd',                      logo: null },
  { code: '090818', name: 'Nexton Microfinance Bank',                logo: null },
  { code: '110019', name: 'NIBSS USSD Payments',                    logo: null },
  { code: '090459', name: 'Nice Microfinance Bank',                  logo: null },
  { code: '090505', name: 'Nigeria Prisons Microfinance Bank',       logo: null },
  { code: '999999', name: 'NIP Virtual Bank',                        logo: null },
  { code: '090194', name: 'NIRSAL Microfinance Bank',                 logo: null },
  { code: '090535', name: 'Nkpolu-Ust Microfinance',                 logo: null },
  { code: '090736', name: 'Nomase MFB',                              logo: null },
  { code: '110028', name: 'Nomba Financial Services Limited',        logo: null },
  { code: '090645', name: 'Nombank MFB',                             logo: null },
  { code: '050030', name: 'Northquest Finance',                       logo: null },
  { code: '090822', name: 'Noun Microfinance Bank',                  logo: null },
  { code: '060003', name: 'Nova Merchant Bank',                       logo: null },
  { code: '090863', name: 'Novel Microfinance Bank',                 logo: null },
  { code: '090734', name: 'Novus MFB',                               logo: null },
  { code: '100032', name: 'NowNow Digital Systems',                  logo: null },
  { code: '070001', name: 'NPF Microfinance Bank',                    logo: null },
  { code: '090491', name: 'Nsuk Microfinance Bank',                  logo: null },
  { code: '090356', name: 'Nsukka Microfinance Bank',                 logo: null },
  { code: '090516', name: 'Numo Microfinance Bank',                  logo: null },
  { code: '090364', name: 'Nuture Microfinance Bank',                 logo: null },
  { code: '090399', name: 'Nwannegadi Microfinance Bank',             logo: null },
  { code: '090437', name: 'Oakland Microfinance Bank',               logo: null },
  { code: '090345', name: 'Oau Microfinance Bank Ltd',                logo: null },
  { code: '090981', name: 'Oba Microfinance Bank',                   logo: null },
  { code: '90755',  name: 'Obeledu MFB',                             logo: null },
  { code: '090810', name: 'Obollo MFB',                              logo: null },
  { code: '090333', name: 'Oche Microfinance Bank',                   logo: null },
  { code: '090576', name: 'Octopus Microfinance Bank Ltd',           logo: null },
  { code: '090738', name: 'Ogberuru MFB',                            logo: null },
  { code: '090739', name: 'Ogige MFB',                               logo: null },
  { code: '090119', name: 'Ohafia Microfinance Bank',                 logo: null },
  { code: '090527', name: 'Ojokoro Microfinance Bank',               logo: null },
  { code: '090565', name: 'Oke-Aro Oredegbe Microfinance Bank Ltd',  logo: null },
  { code: '90348',  name: 'Oko MFB',                                 logo: null },
  { code: '090161', name: 'Okpoga Microfinance Bank',                 logo: null },
  { code: '090566', name: 'Okuku Microfinance Bank Ltd',             logo: null },
  { code: '90752',  name: 'Okwo-Oha MFB',                           logo: null },
  { code: '090272', name: 'Olabisi Onabanjo University MFB',          logo: null },
  { code: '090468', name: 'Olofin Owena Microfinance Bank',          logo: null },
  { code: '090471', name: 'Oluchukwu Microfinance Bank',             logo: null },
  { code: '090460', name: 'Oluyole Microfinance Bank',               logo: null },
  { code: '090295', name: 'Omiye Microfinance Bank',                  logo: null },
  { code: '070007', name: 'Omoluabi Savings and Loans',               logo: null },
  { code: '999992', name: 'OPay',                                     logo: `${CDN}/paycom.png` },
  { code: '305',    name: 'OPay',                                     logo: `${CDN}/paycom.png` },
  { code: '000036', name: 'Optimus Bank',                             logo: null },
  { code: '090492', name: 'Oraukwu Microfinance Bank',               logo: null },
  { code: '090588', name: 'Orisun MFB',                              logo: null },
  { code: '090567', name: 'Orokam Microfinance Bank Ltd',            logo: null },
  { code: '090396', name: 'Oscotech Microfinance Bank',               logo: null },
  { code: '090715', name: 'Osomhe MFB',                              logo: null },
  { code: '090456', name: 'Ospoly Microfinance Bank',                logo: null },
  { code: '090580', name: 'Otech Microfinance Bank Ltd',             logo: null },
  { code: '090542', name: 'Otuo Microfinance Bank Ltd',              logo: null },
  { code: '090767', name: 'Ourpass Microfinance Bank',               logo: null },
  { code: '090346', name: 'Ours MFB',                                 logo: null },
  { code: '327',    name: 'Paga',                                     logo: `${CDN}/paga.png` },
  { code: '070008', name: 'Page Financials',                          logo: null },
  { code: '090497', name: 'Palmcoast Microfinance Bank',             logo: null },
  { code: '999991', name: 'PalmPay',                                  logo: `${CDN}/palmpay.png` },
  { code: '100033', name: 'PalmPay',                                  logo: `${CDN}/palmpay.png` },
  { code: '000030', name: 'Parallex Bank',                            logo: null },
  { code: '090004', name: 'Parallex Microfinance Bank',               logo: null },
  { code: '090390', name: 'Parkway MF Bank',                          logo: null },
  { code: '100003', name: 'Parkway-ReadyCash',                       logo: null },
  { code: '090317', name: 'PatrickGold Microfinance Bank',            logo: null },
  { code: '110001', name: 'PayAttitude Online',                      logo: null },
  { code: '100004', name: 'PayCom',                                   logo: `${CDN}/paycom.png` },
  { code: '090823', name: 'Payrep Microfinance Bank Limited',        logo: null },
  { code: '110006', name: 'Paystack Payments Limited',               logo: null },
  { code: '100039', name: 'Paystack-Titan',                          logo: null },
  { code: '090402', name: 'Peace Microfinance Bank',                  logo: null },
  { code: '090137', name: 'PecanTrust Microfinance Bank',             logo: null },
  { code: '090379', name: 'Peniel Microfinance Bank Ltd',             logo: null },
  { code: '090196', name: 'Pennywise Microfinance Bank',              logo: null },
  { code: '090135', name: 'Personal Trust Microfinance Bank',         logo: null },
  { code: '090165', name: 'Petra Microfinance Bank',                  logo: null },
  { code: '090289', name: 'Pillar Microfinance Bank',                 logo: null },
  { code: '070013', name: 'Platinum Mortgage Bank',                   logo: null },
  { code: '100042', name: 'PocketApp',                               logo: null },
  { code: '050021', name: 'Poder Finance',                            logo: null },
  { code: '076',    name: 'Polaris Bank',                             logo: `${CDN}/polaris-bank.png` },
  { code: '090534', name: 'Polyibadan Microfinance Bank',            logo: null },
  { code: '090296', name: 'Polyuwanna Microfinance Bank',             logo: null },
  { code: '090412', name: 'Preeminent Microfinance Bank',             logo: null },
  { code: '000031', name: 'PremiumTrust Bank',                        logo: null },
  { code: '090274', name: 'Prestige Microfinance Bank',               logo: null },
  { code: '090481', name: 'Prisco Microfinance Bank',                logo: null },
  { code: '090499', name: 'Pristine Divitis Microfinance Bank',      logo: null },
  { code: '090784', name: 'Prodigy MFB',                             logo: null },
  { code: '090503', name: 'Projects Microfinance Bank',              logo: null },
  { code: '090495', name: 'Prospa Capital Microfinance Bank',        logo: null },
  { code: '101',    name: 'ProvidusBank PLC',                        logo: null },
  { code: '090303', name: 'Purplemoney Microfinance Bank',            logo: null },
  { code: '090657', name: 'Pyramid Microfinance Bank',               logo: null },
  { code: '110013', name: 'QR Payments',                             logo: null },
  { code: '090569', name: 'Qube Microfinance Bank Ltd',              logo: null },
  { code: '090850', name: 'Quick Microfinance Bank Limited',         logo: null },
  { code: '090261', name: 'Quickfund Microfinance Bank',              logo: null },
  { code: '090496', name: 'Radalpha Microfinance Bank',              logo: null },
  { code: '090170', name: 'Rahama Microfinance Bank',                 logo: null },
  { code: '502',    name: 'Rand Merchant Bank',                      logo: null },
  { code: '090616', name: 'Rayyan Microfinance Bank',                logo: null },
  { code: '070011', name: 'Refuge Mortgage Bank',                     logo: null },
  { code: '090125', name: 'Regent Microfinance Bank',                 logo: null },
  { code: '090463', name: 'Rehoboth Microfinance Bank',              logo: null },
  { code: '090173', name: 'Reliance Microfinance Bank',               logo: null },
  { code: '090198', name: 'RenMoney Microfinance Bank',               logo: null },
  { code: '090322', name: 'Rephidim Microfinance Bank',               logo: null },
  { code: '110024', name: 'Resident Fintech Limited',                logo: null },
  { code: '90766',  name: 'Retrust MFB',                             logo: null },
  { code: '090449', name: 'Rex Microfinance Bank',                   logo: null },
  { code: '090720', name: 'RIC MFB',                                 logo: null },
  { code: '090132', name: 'Richway Microfinance Bank',                logo: null },
  { code: '090433', name: 'Rigo Microfinance Bank',                  logo: null },
  { code: '090515', name: 'Rima Growth Pathway Microfinance Bank',   logo: null },
  { code: '090443', name: 'Rima Microfinance Bank',                  logo: null },
  { code: '090713', name: 'Rimin Gado Microfinance Bank',            logo: null },
  { code: '090547', name: 'Rockshield Microfinance Bank',            logo: null },
  { code: '090138', name: 'Royal Exchange Microfinance Bank',         logo: null },
  { code: '090175', name: 'Rubies Microfinance Bank',                 logo: null },
  { code: '090286', name: 'Safe Haven MFB',                           logo: null },
  { code: '090485', name: 'Safegate Microfinance Bank',              logo: null },
  { code: '090006', name: 'SafeTrust',                                logo: null },
  { code: '090140', name: 'Sagamu Microfinance Bank',                 logo: null },
  { code: '050003', name: 'Sagegrey Finance Limited',                 logo: null },
  { code: '050024', name: 'Sciart Finance',                           logo: null },
  { code: '090513', name: 'Seap Microfinance Bank',                  logo: null },
  { code: '090112', name: 'Seed Capital Microfinance Bank',           logo: null },
  { code: '090369', name: 'Seedvest Microfinance Bank',               logo: null },
  { code: '090502', name: 'Shalom Microfinance Bank',                logo: null },
  { code: '090748', name: 'Shanono MFB',                             logo: null },
  { code: '090401', name: 'Shepherd Trust Microfinance Bank',         logo: null },
  { code: '090559', name: 'Shield Microfinance Bank Ltd',            logo: null },
  { code: '090558', name: 'Shongom Microfinance Bank Ltd',           logo: null },
  { code: '000034', name: 'Signature Bank',                           logo: null },
  { code: '050008', name: 'Simple Finance Limited',                   logo: null },
  { code: '090339', name: 'Sincere MFB',                              logo: null },
  { code: '120004', name: 'Smartcash Payment Service Bank',          logo: null },
  { code: '090573', name: 'Snow Microfinance Bank',                  logo: null },
  { code: '090506', name: 'Solid Allianze Microfinance Bank',        logo: null },
  { code: '090524', name: 'Solidrock Microfinance Bank',             logo: null },
  { code: '090836', name: 'Sosa Microfinance Bank',                  logo: null },
  { code: '090641', name: 'Source Microfinance Bank',                logo: null },
  { code: '090325', name: 'Sparkle',                                  logo: `${CDN}/sparkle-microfinance-bank.png` },
  { code: '51310',  name: 'Sparkle Microfinance Bank',                logo: `${CDN}/sparkle-microfinance-bank.png` },
  { code: '110026', name: 'Spay Business',                           logo: null },
  { code: '090436', name: 'Spectrum Microfinance Bank',              logo: null },
  { code: '050036', name: 'Spring Sky Finance',                       logo: null },
  { code: '090806', name: 'Springfield Microfinance Bank',           logo: null },
  { code: '100007', name: 'Stanbic IBTC @ease Wallet',               logo: null },
  { code: '221',    name: 'Stanbic IBTC Bank',                        logo: `${CDN}/stanbic-ibtc-bank.png` },
  { code: '068',    name: 'Standard Chartered Bank PLC',              logo: `${CDN}/standard-chartered-bank.png` },
  { code: '090182', name: 'Standard Microfinance Bank',               logo: null },
  { code: '090162', name: 'Stanford Microfinance Bank',               logo: null },
  { code: '090583', name: 'Stateside MFB',                           logo: null },
  { code: '070022', name: 'Stb Mortgage Bank',                        logo: null },
  { code: '090262', name: 'Stellas Microfinance Bank',                logo: null },
  { code: '232',    name: 'Sterling Bank',                            logo: `${CDN}/sterling-bank.png` },
  { code: '090340', name: 'Stockcorp Microfinance Bank',              logo: null },
  { code: '090305', name: 'Sulsap Microfinance Bank',                 logo: null },
  { code: '080003', name: 'Summit Bank',                              logo: null },
  { code: '090302', name: 'Sunbeam Microfinance Bank',                logo: null },
  { code: '100',    name: 'Suntrust Bank',                           logo: null },
  { code: '090446', name: 'Support Mf Bank',                         logo: null },
  { code: '090564', name: 'Supreme Microfinance Bank Ltd',           logo: null },
  { code: '090728', name: 'Sure Anchor MFB',                         logo: null },
  { code: '90757',  name: 'Swift Trust MFB',                         logo: null },
  { code: '090827', name: 'Sycamore Microfinance Bank',              logo: null },
  { code: '100023', name: 'TagPay',                                  logo: null },
  { code: '302',    name: 'TAJ Bank',                                 logo: `${CDN}/taj-bank.png` },
  { code: '000026', name: 'Taj Bank Limited',                         logo: `${CDN}/taj-bank.png` },
  { code: '080002', name: 'Tajwallet',                                logo: null },
  { code: '090560', name: 'Tanadi MFB (Crust)',                      logo: null },
  { code: '090426', name: 'Tangerine Bank',                          logo: null },
  { code: '090593', name: 'Tasued Microfinance Bank Ltd',            logo: null },
  { code: '000042', name: 'Tatum Bank',                               logo: null },
  { code: '110007', name: 'TeamApt',                                 logo: null },
  { code: '100010', name: 'TeasyMobile',                             logo: null },
  { code: '050007', name: 'Tekla Finance Ltd',                        logo: null },
  { code: '090373', name: 'Tf Microfinance Bank',                     logo: null },
  { code: '090283', name: 'Thrive Microfinance Bank',                 logo: null },
  { code: '000025', name: 'Titan Trust Bank',                         logo: null },
  { code: '090801', name: 'Toprate Microfinance Bank',               logo: null },
  { code: '090708', name: 'TransPay Microfinance Bank',              logo: null },
  { code: '090146', name: 'Trident Microfinance Bank',                logo: null },
  { code: '050014', name: 'Trinity Financial Services Limited',       logo: null },
  { code: '090525', name: 'Triple A Microfinance Bank',              logo: null },
  { code: '090327', name: 'Trust Microfinance Bank',                  logo: null },
  { code: '090005', name: 'Trustbond Mortgage Bank',                  logo: null },
  { code: '090276', name: 'Trustfund Microfinance Bank',              logo: null },
  { code: '090315', name: 'U And C Microfinance Bank',                logo: null },
  { code: '90762',  name: 'UBJ MFB',                                 logo: null },
  { code: '090706', name: 'UCEE Microfinance Bank',                  logo: null },
  { code: '090403', name: 'Uda Microfinance Bank',                    logo: null },
  { code: '090782', name: 'Uga Microfinance Bank',                   logo: null },
  { code: '090517', name: 'Uhuru Microfinance Bank',                 logo: null },
  { code: '090820', name: 'Ukpor Microfinance Bank',                 logo: null },
  { code: '090776', name: 'Ultimate Microfinance Bank',              logo: null },
  { code: '090781', name: 'Ultraviolet MFB',                         logo: null },
  { code: '090609', name: 'Ummah Microfinance Bank',                 logo: null },
  { code: '090514', name: 'Umuchinemere Procredit Microfinance Bank',logo: null },
  { code: '090510', name: 'Umunnachi Microfinance Bank',             logo: null },
  { code: '090808', name: 'Umunri MFB',                              logo: null },
  { code: '090814', name: 'Umuoji Microfinance Bank',                logo: null },
  { code: '090331', name: 'Unaab Microfinance Bank',                  logo: null },
  { code: '090778', name: 'Uniabuja MFB',                            logo: null },
  { code: '090266', name: 'Uniben Microfinance Bank',                 logo: null },
  { code: '090193', name: 'Unical Microfinance Bank',                 logo: null },
  { code: '090461', name: 'Uniibadan Microfinance Bank',             logo: null },
  { code: '090452', name: 'Unilag Microfinance Bank',                logo: null },
  { code: '090341', name: 'Unilorin Microfinance Bank',               logo: null },
  { code: '090464', name: 'Unimaid Microfinance Bank',               logo: null },
  { code: '032',    name: 'Union Bank PLC',                           logo: `${CDN}/union-bank-of-nigeria.png` },
  { code: '033',    name: 'United Bank for Africa',                   logo: `${CDN}/united-bank-for-africa.png` },
  { code: '215',    name: 'Unity Bank PLC',                          logo: null },
  { code: '090338', name: 'Uniuyo Microfinance Bank',                 logo: null },
  { code: '090251', name: 'UNN MFB',                                  logo: null },
  { code: '090719', name: 'Unubi MFB',                               logo: null },
  { code: '90765',  name: 'Uvuoma MFB',                              logo: null },
  { code: '090453', name: 'Uzondu Mf Bank',                          logo: null },
  { code: '050020', name: 'Vale Finance Limited',                     logo: null },
  { code: '110015', name: 'Vas2Nets Limited',                        logo: null },
  { code: '110009', name: 'Venture Garden Nigeria Limited',          logo: null },
  { code: '090474', name: 'Verdant Microfinance Bank',               logo: null },
  { code: '090123', name: 'Verite Microfinance Bank',                 logo: null },
  { code: '090110', name: 'VFD Micro Finance Bank',                   logo: null },
  { code: '090813', name: 'Victory Microfinance Bank',               logo: null },
  { code: '090150', name: 'Virtue Microfinance Bank',                 logo: null },
  { code: '090139', name: 'Visa Microfinance Bank',                   logo: null },
  { code: '090787', name: 'Vista Microfinance Bank',                 logo: null },
  { code: '100012', name: 'VTNetworks',                              logo: null },
  { code: '090805', name: 'Wallet Microfinance Bank',                logo: null },
  { code: '090590', name: 'Waya Microfinance Bank Ltd',              logo: null },
  { code: '035',    name: 'Wema Bank PLC',                            logo: `${CDN}/wema-bank.png` },
  { code: '090699', name: 'Wesley MFB',                              logo: null },
  { code: '090741', name: 'Weston-Charis MFB',                       logo: null },
  { code: '090120', name: 'Wetland Microfinance Bank',                logo: null },
  { code: '050035', name: 'Whitecrust Finance',                       logo: null },
  { code: '090419', name: 'Winview Bank',                             logo: null },
  { code: '110029', name: 'Woven Finance',                           logo: null },
  { code: '090201', name: 'Xpress Payments',                          logo: null },
  { code: '090124', name: 'Xslnce Microfinance Bank',                 logo: null },
  { code: '090466', name: 'Yct Microfinance Bank',                   logo: null },
  { code: '110027', name: 'Yello Digital Financial Services',        logo: null },
  { code: '090142', name: 'Yes Microfinance Bank',                    logo: null },
  { code: '090252', name: 'Yobe Microfinance Bank',                   logo: null },
  { code: '090976', name: 'Zain Microfinance Bank',                  logo: null },
  { code: '050019', name: 'Zedvance Finance Limited',                 logo: null },
  { code: '090747', name: 'Zefa MFB',                                logo: null },
  { code: '057',    name: 'Zenith Bank PLC',                          logo: `${CDN}/zenith-bank.png` },
  { code: '100018', name: 'ZenithMobile',                            logo: null },
  { code: '090504', name: 'Zikora Microfinance Bank',                logo: null },
  { code: '100025', name: 'Zinternet Nigeria Limited',               logo: null },
  { code: '090718', name: 'Zitra MFB',                               logo: null },
]

export default bankList
